name: Promote Staging to Production

on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout web repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure master is up to date with staging
        run: |

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout master
          git merge origin/staging --ff-only || git merge origin/staging --no-ff -m "Promote staging to production"
          git push origin master
