name: Update Content in Staging

on:
  repository_dispatch:  # Triggered by webhook from Content repo
    types: [content-updated]

jobs:
  update-submodule-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout web repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update submodule
        run: |
          git submodule update --remote path/to/content-submodule
          git add path/to/content-submodule
          git commit -m "Update content submodule from upstream"
          git push origin HEAD:staging
