name: Update Content in Staging

on:
  repository_dispatch:  # Triggered by webhook from Content repo
    types: [content-updated]

jobs:
  update-submodule-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH for Submodule Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PULL_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout web repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PULL_KEY }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update submodule
        run: |
          git submodule update --remote path/to/content-submodule
          git add path/to/content-submodule
          git commit -m "Update content submodule from upstream" || echo "No changes to commit"
          git push origin HEAD:staging
